# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest
  environment: 'dev'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Use Node.js 18.x'

- script: echo 'hello world'
  displayName: 'hello world'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Compile the project'