steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false